#see https://github.com/andyli/HaxeCI/blob/master/.travis.yml
language: haxe

# TravisCI by default run on linux.
# 
# Let's enable both linux and mac builds because why not?
os:
  - linux

# Let's use Ubuntu Trusty instead of Precise, which reached its EOL on April 28, 2017.
dist: trusty

# Test with Haxe 3.4.7 and Haxe development.
haxe:
  - "3.4.7"
  - development

neko: "2.2.0"

matrix:
  # Allow Haxe development to fail.
  allow_failures:
    - haxe: development

install:  
  - haxelib install uapi/build.hxml
  - haxelib list

script:
  - haxe uapi/build.hxml